services:
  - type: web
    name: brew-crawl-planner-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: openai/gpt-4o-mini
      - key: OPENAI_EMBED_MODEL
        value: text-embedding-3-small
      - key: ENABLE_RAG
        value: "1"
      - key: TAVILY_API_KEY
        sync: false
      - key: SERPAPI_API_KEY
        sync: false
      - key: ARIZE_SPACE_ID
        sync: false
      - key: ARIZE_API_KEY
        sync: false
